Development to master V4
R2D2-2018/ROBOT_ARM pull request #12
Opened 2018-06-19 09:36 UTC by SamZand

It is now possible to display the current position of the arm. With the coordinates we made it possible to do mathematical operators on to three dimensional object. We also cleaned/refactored the code.

2018-06-20 08:07 UTC, JasperSmienk commented
Please remove the + at the beginning of line 6 in the .fetch-build-environment
It causes the tests to not run at all.

2018-06-20 08:12 UTC, JasperSmienk commented on src/coordinate3d.hpp
> +     * @param coord Constatn coordinate to add.
Typo

2018-06-20 08:31 UTC, JasperSmienk commented on src/robot_arm.cpp
> +    this->speed = speed;
Try to avoid using a this pointer when possible.
Instead use something like speed = newSpeed like in the exeuteAction function.

2018-06-20 08:32 UTC, JasperSmienk commented on src/robot_arm.hpp
>       * @param command
Tell something about the command parameter.

2018-06-20 08:33 UTC, JasperSmienk commented on src/robot_arm.hpp
>       * @param action : Actions
Be more descriptive than just 'Actions'
And the : is unnecessary.

2018-06-20 08:34 UTC, JasperSmienk commented on src/robot_arm.hpp
> +     * @param action Action.
Be more descriptive than just 'Actions'

2018-06-20 08:34 UTC, JasperSmienk commented on src/robot_arm.hpp
>       * @return speed
Be more descriptive than just 'speed'

2018-06-20 08:36 UTC, JasperSmienk commented on src/robot_arm.hpp
> +     * @param str Input string.
These @param and @return commands could be more descriptive.

2018-06-20 08:37 UTC, JasperSmienk commented on src/robot_arm.hpp
> +     * @return true Device connected.
Please use only 1 @return command.
e.g. @return Boolean on whether the device is connected or not.

2018-06-20 08:40 UTC, ghost requested changes
Mostly some doxygen updated are needed.
Possibly some more changes are needed after the tests are working.

2018-06-20 08:56 UTC, JasperSmienk commented
I just ran the tests locally and it didn't include the clangformat test, which means that it's still using a old build environment. So that also needs to be updated.

2018-06-22 11:10 UTC, wvanbreukelen commented
@JasperSmienk Unit tests are fixed, but still in a feature branch. The next PR will contain proper testing, as it uses the ```UARLib::MockUART``` object within the build environment.

2018-06-22 11:15 UTC, ghost approved these changes

2018-06-22 11:16 UTC, merged